[package]
name = "systems"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
bevy = { version = "0.8.0" }
rand = "0.8.5"

[features]
default = []
dynamic = ["bevy/dynamic"]